#define DEFINES_H

#define ADC_CHANNEL_COUNT 4  // عدد القنوات
#define MIN_BATTERY_VOL 30.1
#define MAX_BATTERY_VOL 41.9


#define FRONT_LED_PIN GPIO_PIN_13
#define FRONT_LED_PORT GPIOC

#define BUZZER_PIN GPIO_PIN_1
#define BUZZER_PORT GPIOB

#define POWER_BTN_PIN GPIO_PIN_3
#define POWER_BTN_PORT GPIOA

#define SELF_HOLD_PIN GPIO_PIN_4
#define SELF_HOLD_PORT GPIOA

#define THROTTLE_PIN GPIO_PIN_6
#define THROTTLE_PORT GPIOA

#define BREAK_PIN GPIO_PIN_15
#define BREAK_PORT GPIOC

#define BATTERY_V_PIN GPIO_PIN_5
#define BATTERY_V_PORT GPIOA