#define DEFINES_H

#define FRONT_LED_PIN GPIO_PIN_13
#define FRONT_LED_PORT GPIOC

#define BUZZER_PIN GPIO_PIN_1
#define BUZZER_PORT GPIOB

#define POWER_BTN_PIN GPIO_PIN_3
#define POWER_BTN_PORT GPIOA